version: '3.9'

services:
  sgil-proveedores-service:
    build: .
    ports:
      - "8005:8005"
    environment:
      - DB_HOST_URL=postgres
      - DB_NAME=sgil-proveedores
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - PROMETHEUS_MULTIPROC_DIR=/tmp
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/proveedores/health"]  # Ajusta la URL si es necesario
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - sgil_network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sgil-proveedores
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 20s
      retries: 5

    networks:
      - sgil_network


volumes:
  pg_data:

networks:
  sgil_network:
    external: true
