apiVersion: apps/v1
kind: Deployment
metadata:
  name: proveedores
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proveedores
  template:
    metadata:
      labels:
        app: proveedores
    spec:
      containers:
      - name: proveedores
        image: myrepo/proveedores:latest  # Change this to your Docker image
        ports:
        - containerPort: 8005
        envFrom:
        - configMapRef:
            name: proveedores-config
---
apiVersion: v1
kind: Service
metadata:
  name: proveedores-service
spec:
  selector:
    app: proveedores
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8005
  type: ClusterIP  # Change to LoadBalancer if needed
