apiVersion: apps/v1
kind: Deployment
metadata:
  name: proveedores
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proveedores
  template:
    metadata:
      labels:
        app: proveedores
    spec:
      containers:
        - name: proveedores
          image: 996241846882.dkr.ecr.us-east-1.amazonaws.com/sgil-proveedores-service:latest
          ports:
            - containerPort: 8005

      imagePullSecrets:
        - name: regcred 
