apiVersion: apps/v1
kind: Deployment
metadata:
  name: proveedores
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proveedores
  template:
    metadata:
      labels:
        app: proveedores
    spec:
      containers:
        - name: proveedores
          image: 996241846882.dkr.ecr.us-east-1.amazonaws.com/sgil-proveedores-service:latest
          ports:
            - containerPort: 8002

        - name: celery-worker
          image: your-docker-hub-user/sgil-proveedores:v1
          command: ["celery", "-A", "app.tasks", "worker", "--loglevel=info"]
          env:
            - name: CELERY_BROKER_URL
              value: "redis://redis-service:6379/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis-service:6379/0"

      imagePullSecrets:
        - name: regcred 
