apiVersion: v1
kind: Service
metadata:
  name: clientes-service
  namespace: default
spec:
  selector:
    app: clientes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: ClusterIP 