apiVersion: v1
kind: Service
metadata:
  name: sgil-proveedores-service
  namespace: default
spec:
  selector:
    app: proveedores
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8005
  type: ClusterIP 